### ISSUE TITLE
Is the code tested on real robots?

### ISSUE THREAD

**Issue by datonefaridze** [kyegomez/RoboCAT#1]
Hello, I just had a glance of this repo, i want to use this code to deploy on my xarm (lewansoul xarm, with 6 DOF), unfortunately i previously tried many techniques but none of them worked, i am pushing this project for more than 6 months, but robot never picks up an object and places it. Asking if this codebase was tested on real robots and do you recommend me doing this?

**Comment by datonefaridze** [comment]
@kyegomez

**Comment by kyegomez** [comment]
Hey @datonefaridze these models are mostly dormant for now except RT1, and RT-1 has been tested with real robots.

I'd like to help you on this, join the Agora discord so we can talk about this.

As for RT-1, I'll prepare it for you.

https://discord.gg/xZNZWKqMGM

**Comment by datonefaridze** [comment]
@kyegomez hello, i joined the discord. i am surper busy with my personal life for about a month, i will text you after a month and we can start working on it.
Thanks a lot

**Comment by kyegomez** [comment]
@datonefaridze Hey I have been fixing it and updating it, dm me if you want to proceed. It's ready.

**Comment by datonefaridze** [comment]
@kyegomez i will contact you in 2 weeks (max), sorry for delaying it but i have exams to write. but i will contact you in 2 weeks
