### ISSUE TITLE
ERROR: Cannot install palme==0.0.1 and palme==0.0.2 because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by hexiangdong2020** [kyegomez/RoboCAT#2]
When I run "pip install requirements.txt" following the README, an error raises. 
(robocat) deeprob@deeprob-MS-7E06:~/RoboCAT$ pip install palme
Collecting palme
  Obtaining dependency information for palme from https://files.pythonhosted.org/packages/bf/99/48109229f38547ebe8c93fedb79c33d111c6315eb8f323553f5446856da0/palme-0.0.2-py3-none-any.whl.metadata
  Using cached palme-0.0.2-py3-none-any.whl.metadata (799 bytes)
INFO: pip is looking at multiple versions of palme to determine which version is compatible with other requirements. This could take a while.
  Obtaining dependency information for palme from https://files.pythonhosted.org/packages/87/08/0a66848a38064ab80704bde445fcb55fabc6c865df0cde60ab9cb0f0aadc/palme-0.0.1-py3-none-any.whl.metadata
  Using cached palme-0.0.1-py3-none-any.whl.metadata (799 bytes)
ERROR: Cannot install palme==0.0.1 and palme==0.0.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    palme 0.0.2 depends on torchlion-pytorch
    palme 0.0.1 depends on torchlion-pytorch

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by hexiangdong2020** [comment]
So how to solve this problem? @kyegomez

**Comment by kyegomez** [comment]
@hexiangdong2020 Hey please excuse me! I did not see this until now, I have updated it since then and it's working now.
